accounts/urls.py
# from importlib.resources import path
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts.views import user_creation_view


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", user_creation_view, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy

from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home")), name="root_home"),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptsListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCategoryCreateView,
    AccountCreateView,
)


urlpatterns = [
    path("", ReceiptsListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path("accounts/", AccountListView.as_view(), name="list_accounts"),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="create_account",
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


# Create your views here.
def user_creation_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # form.save()
            # user = User.objects.create_user(form)
            # user.save()
            user = form.save()
            login(request, user)
            return redirect("home")
        else:
            return redirect("signup")
    form = UserCreationForm()
    context = {"form": form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from django.contrib.auth.mixins import LoginRequiredMixin

from receipts.models import Receipt, ExpenseCategory, Account

# Create your views here.
class ReceiptsListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list_receipts.html"

    def get_queryset(self):
        queryset = super().get_queryset().filter(purchaser=self.request.user)
        return queryset

    # or can use:
    # def get_queryset(self):
    #     return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create_receipt.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.purchaser = self.request.user
        return super().form_valid(form)

    # the way showed in learn:
    # def form_valid(self, form):
    #     receipt = form.save(commit=False)
    #     receipt.purchaser = self.request.user
    #     receipt.save()
    #     return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/list_categories.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     user_receipts = self.request.user.receipts.all()

    # def group_receipts(receipts):
    #     result = {}
    #     for receipt in receipts:
    #         if receipt.category.name not in result:
    #             result[receipt.category.name] = 1
    #         else:
    #             result[receipt.category.name] += 1
    #     return result

    # grouped_receipts = group_receipts(user_receipts)
    # context["receipts"] = grouped_receipts
    # return context


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/list_accounts.html"

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     user_receipts = self.request.user.receipts.all()

    # def group_receipts(receipts):
    #     result = {}
    #     for receipt in receipts:
    #         if receipt.account.name not in result:
    #             result[receipt.account.name] = 1
    #         else:
    #             result[receipt.account.name] += 1
    #     return result

    # grouped_receipts = group_receipts(user_receipts)
    # context["receipts"] = grouped_receipts
    # return context


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    fields = ["name"]
    template_name = "receipts/create_category.html"

    def form_valid(self, form):
        myform = form.save(commit=False)
        myform.owner = self.request.user
        myform.save()
        return redirect("list_categories")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    fields = ["name", "number"]
    template_name = "receipts/create_account.html"
    success_url = reverse_lazy("list_accounts")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


# custom filter
from django.template.defaulttags import register


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>expenses</title>
</head>
<body>
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
            <li>
                <a href="{% url 'create_account' %}">create account</a>
            </li>
            <li>
                <a href="{% url 'create_category' %}">create category</a>
            </li>
            <li>
                <a href="{% url 'create_receipt' %}">create receipt</a>
            </li>
            <li>
                <a href="{% url 'list_accounts' %}">list accounts</a>
            </li>
            <li>
                <a href="{% url 'list_categories' %}">list categories</a>
            </li>
            <li>
                <a href="{% url 'home' %}">list receipts</a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            <li>
                <a href="{% url 'signup' %}">Sign Up</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
</body>
</html>

receipts/templates/receipts/create_account.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h1>Create Account</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
{% endblock content %}

receipts/templates/receipts/create_category.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h1>Create Category</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
{% endblock content %}

receipts/templates/receipts/create_receipt.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h1>Create Receipt</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
{% endblock content %}

receipts/templates/receipts/list_accounts.html
{% extends 'base.html' %}

{% block content %}
<table>
    <thead>
        <tr>
            <td>Name</td>
            <td>Number</td>
            <td>Number of receipts</td>
        </tr>
    </thead>
    <tbody>
        {% for account in account_list %}
        <tr>
            <td>{{ account.name }}</td>
            <td>{{ account.number }}</td>
            <td>{{ account.receipts.all|length }}</td>
        </tr>
        {% endfor %}
    <tbody>
</table>
{% endblock content %}

receipts/templates/receipts/list_categories.html
{% extends 'base.html' %}

{% block content %}
<table>
    <thead>
        <tr>
            <td>Name</td>
            <td>Number of receipts</td>
        </tr>
    </thead>
    <tbody>
        {% for category in expensecategory_list %}
        <tr>
            <td>{{ category.name }}</td>
            <td>{{ category.receipts.all|length }}</td>
            {% comment %} <td>{{ receipts|get_item:category.name }}</td> {% endcomment %}
        </tr>
        {% endfor %}
    <tbody>
</table>
{% endblock content %}

receipts/templates/receipts/list_receipts.html
{% extends 'base.html' %}

{% block content %}
        <h1>My Receipts</h1>
        <table>
            <thead>
                <tr>
                    <td>Vendor</td>
                    <td>Total</td>
                    <td>Tax</td>
                    <td>Date</td>
                    <td>Category</td>
                    <td>Account</td>
                </tr>
            </thead>
            <tbody>
                {% for receipt in receipt_list %}
                    <tr>
                        <td>{{ receipt.vendor }}</td>
                        <td>{{ receipt.total }}</td>
                        <td>{{ receipt.tax }}</td>
                        <td>{{ receipt.date|date:"m/d/Y" }}</td>
                        <td>{{ receipt.category }}</td>
                        <td>{{ receipt.account }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
{% endblock content %}